sale_purchase_vehicles/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from vehicles_app import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^vehicles_app/',include('vehicles_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicles_app/urls.py
from django.conf.urls import url, include
from vehicles_app import views
from .views import *

# template tagging
app_name = 'vehicles_app'

urlpatterns = [
    url(r'^cars/$', views.cars, name='cars'),
    url(r'^bikes/$', views.bikes, name='bikes'),
    url(r'^trucks/$', views.trucks, name='trucks'),
    url(r'^signUp/$', views.signUp, name='signUp'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^addfile/$', views.addfile, name='addfile'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.FileDelete.as_view(), name='file-delete'),
    url(r'^(?P<post_id>[0-9]+)/data/$', views.data, name='data'),
    url(r'^(?P<post_id>[0-9]+)/update_post/$', views.update_post, name='update_post'),
    url(r'^myposts/$', views.myposts, name='myposts'),
    url(r'^compare/$', views.compare, name='compare'),
    url(r'^frequently_searched/$', views.frequently_searched, name='frequently_searched'),
]

vehicles_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from vehicles_app.models import Posts, UserInfo
from enum import Enum
from django.conf import settings


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')



class AddFile(forms.ModelForm):
    details = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Posts
        fields = ('category','full_name','phone','title','city','price','brand','modelyear','condition','mileage','details','air_conditioner','power_windows','power_steering','automatic_break_system','air_bags','cd_player','image','image1','image2','image3','image4','image5','image6','image7','image8','image9')

vehicles_app/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from vehicles_app.forms import UserForm, AddFile
from .models import Posts, UserInfo
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse, resolve
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import sys
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin


def index(request):
    queryset = Posts.objects.all().order_by('-date')
    #navbar search filter query
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(city__icontains=query) or queryset.filter(title__icontains=query) or queryset.filter(details__icontains=query)
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()


    #sidebar full search filter query
    cat_query = request.GET.get("category")
    city_query = request.GET.get("city")
    brand_query = request.GET.get("brand")
    model_query = request.GET.get("modelyear")
    condition_query = request.GET.get("condition")
    mileage_from_query = request.GET.get("mileagefrom")
    mileage_to_query = request.GET.get("mileageto")
    price_from_query = request.GET.get("pricefrom")
    price_to_query = request.GET.get("priceto")

    if (cat_query and city_query and brand_query and condition_query and mileage_from_query and mileage_to_query and price_from_query and price_to_query) or model_query:
        queryset = queryset.filter(Q(category=cat_query) & Q(city=city_query) & Q(brand=brand_query) & Q(condition=condition_query) or Q(modelyear=model_query))
        queryset = queryset.filter(Q(mileage__gte=mileage_from_query) & Q(price__gte=price_from_query))
        queryset = queryset.filter(Q(mileage__lte=mileage_to_query) & Q(price__lte=price_to_query))
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()



    paginator = Paginator(queryset, 5)
    page = request.GET.get('page' , 1)
    context = paginator.page(page)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request, 'vehicles_app/index.html',  {'context':context, 'queryset':queryset, 'query':query,
                                    'city_query':city_query, 'brand_query':brand_query, 'model_query':model_query,
                                    'condition_query':condition_query, 'mileage_from_query':mileage_from_query,
                                    'mileage_to_query':mileage_to_query, 'price_from_query':price_from_query,
                                    'price_to_query':price_to_query, 'cat_query':cat_query})


def cars(request):
    queryset = Posts.objects.filter(category="cars").order_by('-date')

    #navbar search filter
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(city__icontains=query) or queryset.filter(title__icontains=query) or queryset.filter(details__icontains=query)
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()

    #sidebar full search filter query
    cat_query = request.GET.get("category")
    city_query = request.GET.get("city")
    brand_query = request.GET.get("brand")
    model_query = request.GET.get("modelyear")
    condition_query = request.GET.get("condition")
    mileage_from_query = request.GET.get("mileagefrom")
    mileage_to_query = request.GET.get("mileageto")
    price_from_query = request.GET.get("pricefrom")
    price_to_query = request.GET.get("priceto")

    if (cat_query and city_query and brand_query and condition_query and mileage_from_query and mileage_to_query and price_from_query and price_to_query) or model_query:
        queryset = queryset.filter(Q(category=cat_query) & Q(city=city_query) & Q(brand=brand_query) & Q(condition=condition_query) or Q(modelyear=model_query))
        queryset = queryset.filter(Q(mileage__gte=mileage_from_query) & Q(price__gte=price_from_query))
        queryset = queryset.filter(Q(mileage__lte=mileage_to_query) & Q(price__lte=price_to_query))
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()



    paginator = Paginator(queryset, 5)
    page = request.GET.get('page' , 1)
    context = paginator.page(page)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request, 'vehicles_app/cars.html',  {'context':context, 'queryset':queryset, 'query':query,
                                    'city_query':city_query, 'brand_query':brand_query, 'model_query':model_query,
                                    'condition_query':condition_query, 'mileage_from_query':mileage_from_query,
                                    'mileage_to_query':mileage_to_query, 'price_from_query':price_from_query,
                                    'price_to_query':price_to_query, 'cat_query':cat_query})

def bikes(request):
    queryset = Posts.objects.filter(category="motorbikes").order_by('-date')

    #navbar search filter
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(city__icontains=query) or queryset.filter(title__icontains=query) or queryset.filter(details__icontains=query)
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()

    #sidebar full search filter query
    cat_query = request.GET.get("category")
    city_query = request.GET.get("city")
    brand_query = request.GET.get("brand")
    model_query = request.GET.get("modelyear")
    condition_query = request.GET.get("condition")
    mileage_from_query = request.GET.get("mileagefrom")
    mileage_to_query = request.GET.get("mileageto")
    price_from_query = request.GET.get("pricefrom")
    price_to_query = request.GET.get("priceto")

    if (cat_query and city_query and brand_query and condition_query and mileage_from_query and mileage_to_query and price_from_query and price_to_query) or model_query:
        queryset = queryset.filter(Q(category=cat_query) & Q(city=city_query) & Q(brand=brand_query) & Q(condition=condition_query) or Q(modelyear=model_query))
        queryset = queryset.filter(Q(mileage__gte=mileage_from_query) & Q(price__gte=price_from_query))
        queryset = queryset.filter(Q(mileage__lte=mileage_to_query) & Q(price__lte=price_to_query))
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()

    paginator = Paginator(queryset, 5)
    page = request.GET.get('page' , 1)
    context = paginator.page(page)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request, 'vehicles_app/bikes.html',  {'context':context, 'queryset':queryset, 'query':query,
                                    'city_query':city_query, 'brand_query':brand_query, 'model_query':model_query,
                                    'condition_query':condition_query, 'mileage_from_query':mileage_from_query,
                                    'mileage_to_query':mileage_to_query, 'price_from_query':price_from_query,
                                    'price_to_query':price_to_query, 'cat_query':cat_query})

def trucks(request):
    queryset = Posts.objects.filter(category="trucks").order_by('-date')

    #navbar search filter
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(city__icontains=query) or queryset.filter(title__icontains=query) or queryset.filter(details__icontains=query)
        for q in queryset:
            obj = Posts.objects.get(id=q.id)
            obj.search_counter = obj.search_counter+1
            obj.save()

    #sidebar full search filter query
    cat_query = request.GET.get("category")
    city_query = request.GET.get("city")
    brand_query = request.GET.get("brand")
    model_query = request.GET.get("modelyear")
    condition_query = request.GET.get("condition")
    mileage_from_query = request.GET.get("mileagefrom")
    mileage_to_query = request.GET.get("mileageto")
    price_from_query = request.GET.get("pricefrom")
    price_to_query = request.GET.get("priceto")

    if (cat_query and city_query and brand_query and condition_query and mileage_from_query and mileage_to_query and price_from_query and price_to_query) or model_query:
        queryset = queryset.filter(Q(category=cat_query) & Q(city=city_query) & Q(brand=brand_query) & Q(condition=condition_query) or Q(modelyear=model_query))
        queryset = queryset.filter(Q(mileage__gte=mileage_from_query) & Q(price__gte=price_from_query))

templates/vehicles_app/bikes.html
{% extends "vehicles_app/index.html" %}
{% block body_block %}
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title>My Posts!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}">

    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
<body>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <h2 style="margin-left:300px;">  {{ message }} </h2>
      {% endfor %}
    </ul>
  {% endif %}


  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>

  {% for obj in context %}
  <div class="container" style="padding-left:330px; ;padding-right:0px; width: 100%; margin-bottom: 30px;">
    <div class="well" style=" background-color: rgb(220, 220, 220);">
        <div class="media">
        <div class="media-body">
          <a title="Click for details!" style="text-decoration:none;" href="{% url 'vehicles_app:data' obj.id %}">
          <div class="list-group">
              <div class="d-flex w-100 justify-content-between">
          <h3 class="media-heading" style="margin-top:20px; margin-bottom:20px; color: black;">{{ obj.title }}</h3>
            <div class="w3-content" style="max-width:800px">
                {% if obj.image %}
                   <img style="margin-bottom:30px; float: right" src="{{ obj.image.url }}" width="250" height="250">
                {% endif %}
            </div>
            <p  style="margin-left:10px; color:black; text-overflow: ellipsis;width: 400px;overflow: hidden; white-space: nowrap;"> {{ obj.details }} </p>
            <ul class="list-inline list-unstyled">
              <li>|</li>
              <span style="margin-left:10px;"><i>Brand: {{ obj.brand }} </i></span>
                  <span style="margin-left:10px;"><i>City:{{ obj.city }} </i> </span><br>
                  <li style="margin-left:10px;"><span><i class="glyphicon glyphicon-calendar"></i> {{ obj.date }} </span></li>
              <br><br></a>
                {% if request.user == obj.user or request.user.is_superuser %}
                <br><br>
                <form action="{% url 'vehicles_app:file-delete' obj.id %}" method="post" style="display: inline; left:0; margin-left:10px;">{% csrf_token %} <input type="hidden" name="post_id" value="{{ obj.id }}">
                  <button title="Click to delete!" type="submit" onclick="return confirm('Are you sure you want to delete this Post?')" class="btn btn-danger btn-lg"> <span class="glyphicon glyphicon-trash"></span>Delete</button></form>


                  <form action="{% url 'vehicles_app:update_post' obj.id %}" method="get" style="display: inline; left:0;">{% csrf_token %}<input type="hidden" name="post_id" value="{{ obj.id }}">

                    <button title="Click to edit!" type="submit"  class="btn btn-info btn-lg"> <span class="glyphicon glyphicon-edit"></span>Edit</button></form>
                    {% else %}
                    {% endif %}
                </ul>
             </div>
        </div>
           </div>
         </div>

         </div>
         </div>
         {% empty %}
          <h1 style="margin-top:20px; margin-left:400px; color: black;">No Post Found!</h1>
        {% endfor %}

        <script>
            $(document).on('click', '.confirm-delete', function(){
              return confirm('Are you sure you want to delete this Post?');
            })
        </script>

        <div class="container-fluid">
          <div class="pagin" style="margin-left:600px; ">
          <div class="pagination">
            <span class="step-links">

                {% if query == None and city_query == None %}
                {% if context.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}">previous</a>
                {% endif %}
                {% endif %}

                {% if context.has_previous and query %}
                  {% if query %}
                    <a href="?page=1&q={{query}}">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}&q={{query}}">previous</a>
                  {% else %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}">previous</a>
                  {% endif %}
                {% endif %}

                {% if context.has_previous and city_query %}
                  <a href="?page=1&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">&laquo; first</a>
                  <a href="?page={{ context.previous_page_number }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ context.number }} of {{ context.paginator.num_pages }}.
                </span>

                {% if context.has_next and query %}
                  {% if query %}
                    <a href="?page={{ context.next_page_number }}&q={{query}}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}&q={{query}}">last &raquo;</a>
                  {% else %}
                      <a href="?page={{ context.next_page_number }}">next</a>
                      <a href="?page={{ context.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
                {% endif %}

                {% if context.has_next and city_query %}
                    <a href="?page={{ context.next_page_number }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">last &raquo;</a>
                {% endif %}

                {% if query == None and city_query == None %}
                {% if context.has_next and vehicle_category == None %}
                    <a href="?page={{ context.next_page_number }}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
                {% endif %}


                {% if vehicle_category %}
                {% if city_query == None and query == None %}
                <a href="?page={{ context.next_page_number }}&ctgry={{vehicle_category}}">next</a>
                <a href="?page={{ context.paginator.num_pages }}&ctgry={{vehicle_category}}">last &raquo;</a>
                {% endif %}
                {% endif %}

            </span>
          </div>
          </div>
          </div>


</body>
</html>
{% endblock %}

templates/vehicles_app/cars.html
{% extends "vehicles_app/index.html" %}
{% block body_block %}
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title>My Posts!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}">

    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
<body>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>

  {% for obj in context %}
  <div class="container" style="padding-left:330px; ;padding-right:0px; width: 100%; margin-bottom: 30px;">
    <div class="well" style=" background-color: rgb(220, 220, 220);">
        <div class="media">
        <div class="media-body">
          <a title="Click for details!" style="text-decoration:none;" href="{% url 'vehicles_app:data' obj.id %}">
          <div class="list-group">
              <div class="d-flex w-100 justify-content-between">
          <h3 class="media-heading" style="margin-top:20px; margin-bottom:20px; color: black;">{{ obj.title }}</h3>
            <div class="w3-content" style="max-width:800px">
                {% if obj.image %}
                   <img style="margin-bottom:30px; float: right" src="{{ obj.image.url }}" width="250" height="250">
                {% endif %}
            </div>
            <p style="margin-left:10px; color:black; text-overflow: ellipsis;width: 200px;overflow: hidden; white-space: nowrap;"> {{ obj.details }} </p>
            <ul class="list-inline list-unstyled">
              <li>|</li>
              <span style="margin-left:10px;"><i>Brand: {{ obj.brand }} </i></span>
                  <span style="margin-left:10px;"><i>City:{{ obj.city }} </i> </span><br>
                  <li style="margin-left:10px;"><span><i class="glyphicon glyphicon-calendar"></i> {{ obj.date }} </span></li>
              <br><br></a>
                {% if request.user == obj.user or request.user.is_superuser %}
                <br><br>
                <form action="{% url 'vehicles_app:file-delete' obj.id %}" method="post" style="display: inline; left:0; margin-left:10px;">{% csrf_token %} <input type="hidden" name="post_id" value="{{ obj.id }}">
                  <button title="Click to delete!" type="submit"  onclick="return confirm('Are you sure you want to delete this Post?')" class="btn btn-info btn-lg"> <span class="glyphicon glyphicon-trash"></span>Delete</button></form>


                  <form action="{% url 'vehicles_app:update_post' obj.id %}" method="get" style="display: inline; left:0;">{% csrf_token %}<input type="hidden" name="post_id" value="{{ obj.id }}">

                    <button title="Click to edit!" type="submit"  class="btn btn-info btn-lg"> <span class="glyphicon glyphicon-edit"></span>Edit</button></form>
                    {% else %}
                    {% endif %}
                </ul>
             </div>
        </div>
           </div>
         </div>

         </div>
         </div>
         {% empty %}
          <h1 style="margin-top:20px; margin-left:400px; color: black;">No Post Found!</h1>
        {% endfor %}

        <script>
            $(document).on('click', '.confirm-delete', function(){
              return confirm('Are you sure you want to delete this Post?');
            })
        </script>


        <div class="container-fluid">
          <div class="pagin" style="margin-left:600px; ">
          <div class="pagination">
            <span class="step-links">

                {% if query == None and city_query == None %}
                {% if context.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}">previous</a>
                {% endif %}
                {% endif %}

                {% if context.has_previous and query %}
                  {% if query %}
                    <a href="?page=1&q={{query}}">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}&q={{query}}">previous</a>
                  {% else %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ context.previous_page_number }}">previous</a>
                  {% endif %}
                {% endif %}

                {% if context.has_previous and city_query %}
                  <a href="?page=1&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">&laquo; first</a>
                  <a href="?page={{ context.previous_page_number }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ context.number }} of {{ context.paginator.num_pages }}.
                </span>

                {% if context.has_next and query %}
                  {% if query %}
                    <a href="?page={{ context.next_page_number }}&q={{query}}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}&q={{query}}">last &raquo;</a>
                  {% else %}
                      <a href="?page={{ context.next_page_number }}">next</a>
                      <a href="?page={{ context.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
                {% endif %}

                {% if context.has_next and city_query %}
                    <a href="?page={{ context.next_page_number }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}&category={{cat_query}}&city={{city_query}}&brand={{brand_query}}&modelyear={{model_query}}&condition={{condition_query}}&mileagefrom={{mileage_from_query}}&mileageto={{mileage_to_query}}&pricefrom={{price_from_query}}&priceto={{price_to_query}}">last &raquo;</a>
                {% endif %}

                {% if query == None and city_query == None %}
                {% if context.has_next and vehicle_category == None %}
                    <a href="?page={{ context.next_page_number }}">next</a>
                    <a href="?page={{ context.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
                {% endif %}


                {% if vehicle_category %}
                {% if city_query == None and query == None %}
                <a href="?page={{ context.next_page_number }}&ctgry={{vehicle_category}}">next</a>
                <a href="?page={{ context.paginator.num_pages }}&ctgry={{vehicle_category}}">last &raquo;</a>
                {% endif %}
                {% endif %}

            </span>
          </div>
          </div>
          </div>


</body>
</html>
{% endblock %}

templates/vehicles_app/user_login.html
{% extends "vehicles_app/index.html" %}
{% block body_block %}
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>LogIn Form!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}">

    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
<body>
  <div class="container">
          <div class="row centered-form">
          <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-4">
          	<div class="panel panel-default">
          		<div style="background-color:rgb(220, 220, 220)" class="panel-heading">
  			    		<h3 class="panel-title">Please Log In here!</h3>
  			 			</div>
  			 			<div style="background-color:rgb(220, 235, 220)" class="panel-body">
                <form role="form" method="post" action="{% url 'vehicles_app:user_login' %}">
                      {% csrf_token %}
                  <div class="row">
                    <div class="form-group">
                      <input type="text" name="username" class="form-control input-sm" placeholder="Enter username" required><br>

                          <div class="form-group">
                            <input type="password" name="password" class="form-control input-sm" placeholder="Password" required><br>


                        <input type="submit" value="Submit" id="submit" style="margin-left:150px; width: 20%" class="btn btn-info"> <input type="reset" value="Reset" id="reset" style="margin-left:40px; width: 20%" class="btn btn-danger">
                      </div>
                      </div>
                      </div>
                    </form>

  	    		</div>
      		</div>
      </div>
      </div>




</body>
</html>
{% endblock %}